// This file was auto-generated by `gen-tests.py`, do not edit manually.

#[allow(non_snake_case)]

use crate::*;

#[test] fn noto_sans_regular_glyph_outlines_all_glyphs() {glyph_outlines_all_glyphs("NotoSans-Regular.ttf")}
#[test] fn noto_sans_regular_glyph_outlines_single_glyphs() {glyph_outlines_single_glyphs("NotoSans-Regular.ttf")}
#[test] fn noto_sans_c_j_ksc_regular_glyph_outlines_all_glyphs() {glyph_outlines_all_glyphs("NotoSansCJKsc-Regular.otf")}
#[test] fn noto_sans_c_j_ksc_regular_glyph_outlines_single_glyphs() {glyph_outlines_single_glyphs("NotoSansCJKsc-Regular.otf")}
#[test] fn roboto_regular_glyph_outlines_all_glyphs() {glyph_outlines_all_glyphs("Roboto-Regular.ttf")}
#[test] fn roboto_regular_glyph_outlines_single_glyphs() {glyph_outlines_single_glyphs("Roboto-Regular.ttf")}
#[test] fn latin_modern_roman_regular_glyph_outlines_all_glyphs() {glyph_outlines_all_glyphs("LatinModernRoman-Regular.otf")}
#[test] fn latin_modern_roman_regular_glyph_outlines_single_glyphs() {glyph_outlines_single_glyphs("LatinModernRoman-Regular.otf")}
#[test] fn deja_vu_sans_mono_glyph_outlines_all_glyphs() {glyph_outlines_all_glyphs("DejaVuSansMono.ttf")}
#[test] fn deja_vu_sans_mono_glyph_outlines_single_glyphs() {glyph_outlines_single_glyphs("DejaVuSansMono.ttf")}
#[test] fn clicker_script_regular_glyph_outlines_all_glyphs() {glyph_outlines_all_glyphs("ClickerScript-Regular.ttf")}
#[test] fn clicker_script_regular_glyph_outlines_single_glyphs() {glyph_outlines_single_glyphs("ClickerScript-Regular.ttf")}
#[test] fn m_p_l_u_s1p_regular_glyph_outlines_all_glyphs() {glyph_outlines_all_glyphs("MPLUS1p-Regular.ttf")}
#[test] fn m_p_l_u_s1p_regular_glyph_outlines_single_glyphs() {glyph_outlines_single_glyphs("MPLUS1p-Regular.ttf")}
