// This file was auto-generated by `gen-tests.py`, do not edit manually.

#[allow(non_snake_case)]
use crate::*;

#[test]
fn latin_modern_roman_regular_1() {
    test_cff_dump("LatinModernRoman-Regular.otf", "290,292", 1)
}
#[test]
fn latin_modern_roman_regular_2() {
    test_cff_dump("LatinModernRoman-Regular.otf", "580", 2)
}
#[test]
fn new_c_m_math_regular_1() {
    test_cff_dump("NewCMMath-Regular.otf", "1034,4789", 1)
}
#[test]
fn noto_sans_c_j_ksc_regular_1() {
    test_cff_dump("NotoSansCJKsc-Regular.otf", "230-232", 1)
}
